import click
import psutil
import toml
import uuid
import time
import hashlib
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Tuple, Optional
from cryptography.fernet import Fernet


def _sanitize_dict(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Sanitize a dictionary by removing or masking sensitive keys.

    Args:
        data: The raw dictionary to sanitize.

    Returns:
        The sanitized dictionary.
    """
    sensitive_patterns = ['password', 'secret', 'key', 'token', 'api_key', 'private_key']
    sanitized = {}
    for key, value in data.items():
        if any(pattern in key.lower() for pattern in sensitive_patterns):
            sanitized[key] = "***REDACTED***"
        else:
            sanitized[key] = value
    return sanitized


def _capture_environment_details() -> Dict[str, Any]:
    """
    Capture detailed information about the current development environment.

    This includes system metrics, environment variables, and running processes.

    Returns:
        A dictionary containing system and environment details.
    """
    details = {
        "timestamp": datetime.now().isoformat(),
        "hostname": psutil.cpu_percent(interval=1)
    }
    details["memory"] = {
        "total": psutil.virtual_memory().total,
        "used": psutil.virtual_memory().used,
        "percent": psutil.virtual_memory().percent
    }
    details["cpu"] = {
        "count": psutil.cpu_count(),
        "cores": psutil.cpu_count(logical=False),
        "load": psutil.getloadavg() if hasattr(psutil, 'getloadavg') else []
    }
    
    env_vars = dict(psutil.Process().environ)
    details["environment_variables"] = _sanitize_dict(env_vars)
    
    details["packages"] = {
        "installed_count": len(psutil.process_iter()),
        "uptime_seconds": psutil.boot_time()
    }
    return details


def _create_encryption_key() -> bytes:
    """
    Generate a new Fernet encryption key for snapshot security.

    Returns:
        The generated bytes key.
    """
    return Fernet.generate_key()


def _encrypt_data(key: bytes, data: Dict[str, Any]) -> bytes:
    """
    Encrypt the snapshot data using a Fernet symmetric key.

    Args:
        key: The Fernet key used for encryption.
        data: The dictionary data to encrypt.

    Returns:
        The encrypted byte string.
    """
    fernet = Fernet(key)
    serialized = toml.dumps(data)
    return fernet.encrypt(serialized.encode())


def _get_unique_reference_id() -> str:
    """
    Generate a UUID to serve as a unique reference ID for the snapshot.

    Returns:
        The string representation of the UUID.
    """
    return str(uuid.uuid4())


@click.command(name="share")
@click.option("--output-path", "-o", default=None, type=Path, help="Output path for the snapshot artifact.")
def share_snapshot(output_path: Optional[Path]) -> None:
    """
    Execute a share command to snapshot the local development environment.

    This command captures system state, encrypts sensitive data, exports the
    artifact to a shareable file, and generates a unique reference ID for
    reproducibility tracking.

    Args:
        output_path: Optional path where the snapshot file should be saved.
    """
    try:
        if output_path is None:
            output_path = Path.cwd() / "snapshot" / f"snapshot_{datetime.now().strftime('%Y%m%d_%H%M%S')}.toms"
            output_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            output_path.parent.mkdir(parents=True, exist_ok=True)

        reference_id = _get_unique_reference_id()
        system_data = _capture_environment_details()
        encryption_key = _create_encryption_key()
        
        encrypted_content = _encrypt_data(encryption_key, system_data)

        artifact_path = str(output_path / f"{reference_id}.snapshot")
        
        with open(artifact_path, "wb") as f:
            f.write(encrypted_content)

        key_path = str(output_path / f"{reference_id}.key")
        with open(key_path, "wb") as f:
            f.write(encryption_key)

        click.echo(click.style("SUCCESS", fg="green"))
        click.echo(f"Artifact Created: {artifact_path}")
        click.echo(f"Unique Reference ID: {reference_id}")
        click.echo(f"Encryption Key Saved: {key_path}")
        click.echo(click.style("SECURITY NOTE: Keep the .key file separate from the .snapshot file.", fg="yellow"))

    except PermissionError:
        click.echo(click.style("ERROR: Permission denied to write files.", fg="red"))
        raise click.ClickException("Permission denied")
    except FileNotFoundError:
        click.echo(click.style("ERROR: Output directory path does not exist.", fg="red"))
        raise click.ClickException("Output directory not found")
    except Exception as e:
        click.echo(click.style(f"ERROR: Failed to create snapshot: {str(e)}", fg="red"))
        raise click.ClickException("Snapshot creation failed")